import axios from 'axios'
import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.css'
import CustomChart, { ChartData } from '../components/CustomChart'
import { useRouter } from 'next/router'
import Image from 'next/image'

export async function getServerSideProps({ query }: any) {
  try {
    if (query.from && query.to) {
      const data = await getData(query.from, query.to)
      return { props: { data } }
    }
    const data = await getData()
    return {
      props: {
        data,
      },
    }
  } catch (error) {
    console.log(error)
    return {
      notFound: true,
    }
  }
}

async function getData(from: string = '2022-04-01', to: string = '2022-04-06') {
  let url = `${process.env.API_URL}/api/chart-query?to=${to}&from=${from}`
  const res = await axios.get(url)
  return res.data.aggregations['0'].buckets
}

function Home({ data }: any) {
  const [chartData, setChartData] = React.useState<ChartData>({} as ChartData)
  const [renderChart, setRenderChart] = React.useState(false)
  const [fromDate, setFromDate] = React.useState('2022-04-01')
  const [toDate, setToDate] = React.useState('2022-04-06')

  const router = useRouter()

  React.useEffect(() => {
    setRenderChart(false)
    const labels = data[0]['1']?.buckets
      .filter((d: any) => d.doc_count > 0)
      .map((key: any) => key.key_as_string.substring(0, 10))

    const series = data.map((d: any) => {
      return {
        name: d.key,
        data: d['1']?.buckets
          .filter((doc: any) => doc.doc_count > 0)
          .map((key: any) => key['2']?.value),
      }
    })
    setChartData({
      labels,
      series,
    })
  }, [data, router.query])

  React.useEffect(() => {
    setRenderChart(true)
  }, [chartData])

  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify Top 200 streams</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input
          type="date"
          value={fromDate}
          onChange={(e) => setFromDate(e.target.value)}
        />
        <input
          type="date"
          value={toDate}
          onChange={(e) => setToDate(e.target.value)}
        />
        <button onClick={() => router.push(`?from=${fromDate}&to=${toDate}`)}>
          Dates
        </button>
        {renderChart && <CustomChart data={chartData} />}
      </main>
    </div>
  )
}

export default Home
